CREATE TABLE IF NOT EXISTS personagem (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    classe VARCHAR(100) NOT NULL,
    raca VARCHAR(100) NOT NULL,
    nivel INT NOT NULL,
    forca INT NOT NULL,
    dex INT NOT NULL,
    con INT NOT NULL,
    inte INT NOT NULL,
    sab INT NOT NULL,
    car INT NOT NULL,
    data_criacao DATE
);

CREATE TABLE IF NOT EXISTS companheiro (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    classe VARCHAR(100) NOT NULL,
    raca VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS party (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    personagem_id INT NOT NULL,
    companheiro_id INT NOT NULL,
    FOREIGN KEY (personagem_id) REFERENCES personagem(id),
    FOREIGN KEY (companheiro_id) REFERENCES companheiro(id)
);

INSERT INTO companheiro (nome, classe, raca) VALUES
    ('Astarion', 'Ladino', 'Elfo'),
    ('Gale', 'Mago', 'Humano'),
    ('Karlach', 'Bárbara', 'Tiefling'),
    ('Lae''zel', 'Guerreira', 'Githyanki'),
    ('Umbralma', 'Clériga', 'Meio-Elfa'),
    ('Wyll', 'Bruxo', 'Humano'),
    ('Halsin', 'Druida', 'Elfo da Floresta'),
    ('Jaheira', 'Druida', 'Meio-Elfa'),
    ('Minsc', 'Patrulheiro', 'Humano'),
    ('Minthara', 'Paladina', 'Drow');